### ISSUE TITLE
`font: sans-serif` not working (Invalid value)

### ISSUE THREAD

**Issue by pReya** [fabianmichael/kirby-markdown-field#126]
I just wanted to try out the sans-serif font option, however it is not working for me:

This is my blueprint:
```YAML
title: Default Page
preset: page
fields:
  text:
    label: Text
    type: markdown
    size: large
    font: sans-serif
    buttons:
     - bold

```

When I open the panel, I am greeted with this:

```
Error in "text" field.

Invalid value for "font" in file: /Users/moritz/Code/fabcity-wiki-kirby/kirby/src/Toolkit/Component.php line: 187
```
