### ISSUE TITLE
Feature Request: Option to set file/image template

### ISSUE THREAD

**Issue by owzim** [fabianmichael/kirby-markdown-field#133]
Right now when uploading a file or image, it will get uploaded without accompanying template file. 

It would be very useful to be able to set the template in field options.

**Comment by fabianmichael** [comment]
This should really work like in the normal textarea field. I’ll have a look soon.

**Comment by tobimori** [comment]
This works for me in the latest version:

```
files: page('page://images').images
uploads:
  template: image
  parent: page('page://images')

```
