### ISSUE TITLE
Get field not loaded

### ISSUE THREAD

**Issue by janstieler** [fabianmichael/kirby-markdown-field#149]
Hi,
I installed the plugin with composer and if I call a field wit the type `markdown` I get the error:
![Bildschirmfoto 2022-07-04 um 05 19 48](https://user-images.githubusercontent.com/754880/177075836-9e4c168f-f88a-4dd0-9c2a-c705f9fdf48f.jpg)
with this blueprint:
```yml
adressdescription:
  label: Beschreibung
  type: markdown
```
this are the system output in kirby:
![Bildschirmfoto 2022-07-04 um 05 22 17](https://user-images.githubusercontent.com/754880/177076014-dc4a5dd4-802a-4642-a801-6a76584c7dd8.jpg)

Cheers
