### ISSUE TITLE
File upload broken

### ISSUE THREAD

**Issue by nilshoerrmann** [fabianmichael/kirby-markdown-field#159]
When uploading an image via the Markdown field, I get the following error:

![Bildschirmfoto am 2022-11-23 um 14 29 06](https://user-images.githubusercontent.com/25466/203558844-fa864ab3-aae3-4aec-95e2-e49788acea3f.png)

The upload endpoint returns a 404 error:

```
POST http://localhost:8888/api//pages/news+title/fields/preface/upload [HTTP/1.1 404 Not Found 0ms]
```

I see that the path is not correct, it should be `http://localhost:8888/example.com/api/pages/news+title/fields/preface/upload` – the path to my install is missing.

**Comment by fabianmichael** [comment]
@nilshoerrmann Does this issue still affect you/which Kirby version was/is affected?

**Comment by nilshoerrmann** [comment]
I'll be working again on that project next week and will check again, but I think it still affects us.

**Comment by nilshoerrmann** [comment]
This happened on Kirby 3.7.5 – I'll try the newest version next week to see if that fixes the issue.

**Comment by nilshoerrmann** [comment]
I finally found the time to check this issue again and, yes, this problem still exists. I'm not able to update this specific install to Kirby 3.9 yet so this is happening on Kirby 3.7.5 currently.

Two things to note:

1. We are using the Markdown field within a [module](https://github.com/medienbaecker/kirby-modules/).
2. We are uploading to the grandparent of the given page. This is the blueprint:

```yml
title: 'Feature: News'
fields:
  text:
    type: markdown
    label: Text
    size: small
    help: 'To insert image in text, use the paperclip. Remember to have a line space before and after, or it will not show up.'
    files: page.parent.parent.images
    uploads:
      parent: page.parent.parent
```
