### ISSUE TITLE
pagelink dialog does not return results

### ISSUE THREAD

**Issue by MacGyer** [fabianmichael/kirby-markdown-field#170]
Hello,

I am using kirby-markdown-field and have enabled the pagelink button.

Unfortunately, there is no page to select, as the API calls returns an 404.

![grafik](https://github.com/fabianmichael/kirby-markdown-field/assets/2939625/073bc40d-abdb-4c84-89af-b30795d78258)

The actual  API call:
`http://redacted-domain.com/api/pages/home/fields/contentblocks/fieldsets/markdown/fields/text/pages?page=0`

![grafik](https://github.com/fabianmichael/kirby-markdown-field/assets/2939625/9462c55d-3634-41ed-b991-b2897d4fcfd5)

Following is the blueprint file in `blueprints/fields` which is then used in the actual field via `extends`:

```yml
buttons:
    headlines:
        - h1
        - h2
        - h3
        - h4
        - h5
        - h6
    bold: '**'
    italic: '_'
    ul: '-'
    ol: true
    link:
        blank: true
    pagelink: true
    blockquote: true
    hr: '---'
size: medium
```

How do I configure the pagelink button?

What else do you need to inspect the issue?

Thanks in advance.
