### ISSUE TITLE
[K4] 4.0 Compatibility

### ISSUE THREAD

**Issue by afbora** [fabianmichael/kirby-markdown-field#174]
> Cannot read properties of undefined (reading 'map')
> Cannot read properties of undefined (reading 'page')

````yaml
fields:
  text:
    type: markdown
````

Kirby 4.0.0-beta.1 (`v4/develop` branch)
