### ISSUE TITLE
Having 2 dividers does not work with the Symfony YAML parser

### ISSUE THREAD

**Issue by tobimori** [fabianmichael/kirby-markdown-field#180]
![CleanShot 2024-02-09 at 17 35 24@2x](https://github.com/fabianmichael/kirby-markdown-field/assets/29142128/dfc8b00e-d29b-44c9-b277-dc993efd023b)

**Comment by tobimori** [comment]
This works, but is not documented anywhere:
![CleanShot 2024-02-10 at 00 20 26@2x](https://github.com/fabianmichael/kirby-markdown-field/assets/29142128/314d4488-8688-49fa-8d8d-8ee420746ecb)

**Comment by fabianmichael** [comment]
@tobimori I just tried Kirby 4.1.1 and it worked with this blueprint. Please check your indentation:

```yaml
fields:
  ta:
    type: markdown
    buttons:
      headlines:
        - h1
      - divider
      bold: ** # or `__`
      - divider
      link: null # or `markdown` or `kirbytext`
```

Kirby 4 seems to use the Symfony YAML parser (https://github.com/getkirby/kirby/blob/main/composer.json#L49) by default, did I miss anything?
